name: "[CI] Continuous Integration"
on:
    pull_request:
        types: [opened, synchronize]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: "Run lint"
              run: "echo 'Teste'"
